### ISSUE TITLE
What connector is on the thermistor?

### ISSUE THREAD

**Issue by kozross** [elegooofficial/neptune3pro#2]
I'm a bit unclear what connector is used to connect the thermistor to the toolhead PCB: the BOM for the printer and the toolhead PCB seem to disagree on this. Could you please clarify?

**Comment by Tweako** [comment]
It's listed in the wire diagram.
https://github.com/elegooofficial/neptune3pro/blob/main/Wire/Thermistor_Nozzle.pdf

**Comment by kozross** [comment]
@Tweako - thanks!
